##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: https://eugestumm.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /BajubaDigitalArchive 
# location of code, the full url to your github repository
source-code: https://github.com/eugestumm/BajubaDigitalArchive

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Bajubá Digital Archive

# tagline, a short phrase that will appear throughout the site in the top banner
tagline: An Open-Access Repository for Resources in and on Pajubá (or Bajubá)
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This digital archive features cultural productions and academic works that center around Pajubá. Pajubá (or Bajubá) is a cryptolect originally developed by Brazilian trans women and travestis to protect themselves from violence and persecution. All metadata in this project is licensed under Creative Commons CC-BY 4.0."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Euge Stumm

# Set up site language ids and display names. First language will be the site's default language
site_languages:
  - lang_id: en
    lang_display: English
  - lang_id: pt
    lang_display: Português
    lang_site_title: Arquivo Digital Bajubá
    lang_site_tagline: Um repositório de acesso aberto para recursos em e sobre o Pajubá (ou Bajubá)
    lang_site_description: "Este arquivo digital apresenta produções culturais e trabalhos acadêmicos que se centram em torno do Pajubá. O Pajubá (ou Bajubá) é um cryptolect originalmente desenvolvido por mulheres trans brasileiras e travestis para se protegerem da violência e perseguição. Todos os metadados deste projeto estão licenciados sob Creative Commons CC-BY 4.0."
# Set paths, language ids, and permalinks for pages
defaults:
  -
    scope:
      path: 'pt'
    values:
      permalink: /pt/:basename
      lang: 'pt'
  -
    scope:
      path: 'pages'
    values:
      lang: 'en'

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: books-metadata


##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
#organization-name: "Arte Público Press"
#organization-link: https://artepublicopress.com/
#organization-logo-banner: /assets/img/APP_Logo_2019.png
#organization-logo-nav: /assets/img/app_logo_white_sm.png


##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: false

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
